apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRequiredCrossLabel
metadata:
  name: payments-current-policy
  annotations:
    governance.example/policy-version: pi-8
spec:
  enforcementAction: dryrun
  match:
    kinds:
      - apiGroups: ["apps"]
        kinds: ["Deployment"]
    namespaces: ["payments"]
  parameters:
    label: governance-generation
    value: v8
