#!/usr/bin/env python3
"""Regenerate the transition-control table from per-poll observations."""

from __future__ import annotations

import json
from collections import defaultdict
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
RESULTS = ROOT / "lab/results_transition"
document = json.loads((RESULTS / "transition_observations.json").read_text())
rows = document["rows"]
windows = document["summary"]["windows_metadata"]
window_map = {int(row["window"]): row for row in windows}
grouped = defaultdict(list)
for row in rows:
    if row["completed_mono"] >= window_map[int(row["window"])]["action_started_mono"]:
        grouped[row["control"]].append(row)

lines = [
    "% Generated by scripts/analyze_transition_controls.py",
    r"\begin{tabular}{@{}lrrrrr@{}}",
    r"\toprule",
    r"Control & Windows & Polls & Gov. drift & Config. convergence & Epistemic \\",
    r"\midrule",
]
summary = []
for control in sorted(grouped):
    subset = grouped[control]
    governance = sum(
        row["verdict"] == "drift"
        and any(
            label in {"policy", "authorization", "intent", "environment"}
            for label in row.get("class_set", [])
        )
        for row in subset
    )
    configuration = sum(
        "configuration" in row.get("class_set", []) for row in subset
    )
    epistemic = sum(row["verdict"] == "undecidable" for row in subset)
    count = len({int(row["window"]) for row in subset})
    lines.append(
        f"{control} & {count} & {len(subset)} & {governance} & "
        f"{configuration} & {epistemic} " + r"\\"
    )
    summary.append({
        "control": control,
        "windows": count,
        "polls_transition_and_post": len(subset),
        "substantive_governance_alarm_polls": governance,
        "configuration_convergence_polls": configuration,
        "epistemic_warning_polls": epistemic,
    })
lines += [r"\bottomrule", r"\end{tabular}"]
(RESULTS / "table_transition_controls.tex").write_text("\n".join(lines) + "\n")
(RESULTS / "transition_analysis.json").write_text(json.dumps({
    "source_campaign": document["campaign"],
    "controls": summary,
}, indent=2) + "\n")
print(json.dumps(summary, indent=2))
