#!/usr/bin/env python3
"""Validate and summarize the synthetic batch-evaluator microbenchmark."""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import math
import statistics
from collections import defaultdict
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_RESULTS = ROOT / "lab" / "results_scaling"
BENCHMARKS = ("sweep", "fanout_total", "fanout_subset")


def quantile(values: list[float], probability: float) -> float:
    """Linear interpolation on zero-indexed ranks (NumPy's default method)."""

    if not values:
        raise ValueError("cannot summarize an empty sample")
    ordered = sorted(values)
    position = (len(ordered) - 1) * probability
    lower = math.floor(position)
    upper = math.ceil(position)
    if lower == upper:
        return ordered[lower]
    weight = position - lower
    return ordered[lower] * (1.0 - weight) + ordered[upper] * weight


def summarize_rows(rows: list[dict[str, Any]]) -> dict[str, Any]:
    durations = [float(row["milliseconds"]) for row in rows]
    rates = [float(row["units_per_second"]) for row in rows]
    affected = {int(row["affected_units"]) for row in rows}
    calls = {int(row["modeled_external_calls"]) for row in rows}
    naive_calls = {int(row["modeled_naive_external_calls"]) for row in rows}
    if len(affected) != 1 or len(calls) != 1 or len(naive_calls) != 1:
        raise SystemExit("inconsistent unit or call model within one benchmark cell")
    return {
        "samples": len(rows),
        "affected_units": affected.pop(),
        "milliseconds_p50": quantile(durations, 0.50),
        "milliseconds_p95": quantile(durations, 0.95),
        "milliseconds_p99": quantile(durations, 0.99),
        "milliseconds_mean": statistics.fmean(durations),
        "units_per_second_median": statistics.median(rates),
        "units_per_second_p05": quantile(rates, 0.05),
        "modeled_external_calls": calls.pop(),
        "modeled_naive_external_calls": naive_calls.pop(),
    }


def verify_csv(results: Path, json_rows: list[dict[str, Any]]) -> None:
    with (results / "scaling_raw.csv").open(newline="") as handle:
        csv_rows = list(csv.DictReader(handle))
    if len(csv_rows) != len(json_rows):
        raise SystemExit("raw CSV/JSON row counts differ")
    keys = list(csv_rows[0]) if csv_rows else []
    for index, (csv_row, json_row) in enumerate(zip(csv_rows, json_rows), start=1):
        projected = {key: str(json_row[key]) for key in keys}
        if csv_row != projected:
            raise SystemExit(f"raw CSV differs from JSON at row {index}")


def validate(payload: dict[str, Any], results: Path) -> None:
    if "in-memory" not in payload.get("experiment", ""):
        raise SystemExit("experiment is not labeled as an in-memory microbenchmark")
    scope = payload.get("measurement_scope", "")
    for excluded in ("No Kubernetes", "network", "serialization"):
        if excluded not in scope:
            raise SystemExit(f"measurement boundary omits {excluded!r}")
    expected_sources = {
        "run_scaling_experiment.py": hashlib.sha256(
            (ROOT / "lab/run_scaling_experiment.py").read_bytes()
        ).hexdigest(),
        "batch_evaluator.py": hashlib.sha256(
            (ROOT / "lab/batch_evaluator.py").read_bytes()
        ).hexdigest(),
    }
    if payload.get("source_sha256") != expected_sources:
        raise SystemExit("scaling campaign source hashes do not match the frozen implementation")
    records = payload.get("records", [])
    expected = len(payload["sizes"]) * int(payload["repetitions"]) * len(BENCHMARKS)
    if len(records) != expected:
        raise SystemExit(f"expected {expected} raw rows, found {len(records)}")
    seen: set[tuple[int, int, str]] = set()
    for row in records:
        key = (int(row["n"]), int(row["repetition"]), str(row["benchmark"]))
        if key in seen:
            raise SystemExit(f"duplicate raw cell: {key}")
        seen.add(key)
        if row["benchmark"] not in BENCHMARKS:
            raise SystemExit(f"unknown benchmark: {row['benchmark']}")
        if int(row["exact_vectors"]) != int(row["expected_vectors"]):
            raise SystemExit(f"non-exact vector in raw cell: {key}")
        if float(row["milliseconds"]) <= 0 or float(row["units_per_second"]) <= 0:
            raise SystemExit(f"non-positive timing in raw cell: {key}")
    verify_csv(results, records)


def fmt_rate(value: float) -> str:
    return f"{value:,.0f}".replace(",", r"\,")


def write_tables(results: Path, summary: dict[str, Any]) -> None:
    scaling = [
        "% Generated by scripts/analyze_scaling.py; calls are modeled, not observed.",
        r"\begin{tabular}{@{}rrrrrrrr@{}}",
        r"\toprule",
        "$n$ & Reps & P50 ms & P95 ms & P99 ms & Units/s & "
        "Batch calls$^*$ & Per-unit calls$^*$ \\\\",
        r"\midrule",
    ]
    for item in summary["sweep"]:
        scaling.append(
            f"{item['n']} & {item['samples']} & {item['milliseconds_p50']:.3f} & "
            f"{item['milliseconds_p95']:.3f} & {item['milliseconds_p99']:.3f} & "
            f"{fmt_rate(item['units_per_second_median'])} & "
            f"{item['modeled_external_calls']} & {item['modeled_naive_external_calls']} \\\\"
        )
    scaling += [r"\bottomrule", r"\end{tabular}"]
    (results / "table_scaling.tex").write_text("\n".join(scaling) + "\n")

    fanout = [
        "% Generated by scripts/analyze_scaling.py; prepared-index event path.",
        r"\begin{tabular}{@{}rrrrrrr@{}}",
        r"\toprule",
        "$n$ & Total $k$ & Total P95 ms & Total units/s & Subset $k$ & "
        "Subset P95 ms & Subset units/s \\\\",
        r"\midrule",
    ]
    total = {item["n"]: item for item in summary["fanout_total"]}
    subset = {item["n"]: item for item in summary["fanout_subset"]}
    for n in sorted(total):
        all_item, part_item = total[n], subset[n]
        fanout.append(
            f"{n} & {all_item['affected_units']} & {all_item['milliseconds_p95']:.3f} & "
            f"{fmt_rate(all_item['units_per_second_median'])} & "
            f"{part_item['affected_units']} & {part_item['milliseconds_p95']:.3f} & "
            f"{fmt_rate(part_item['units_per_second_median'])} \\\\"
        )
    fanout += [r"\bottomrule", r"\end{tabular}"]
    (results / "table_fanout.tex").write_text("\n".join(fanout) + "\n")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--results-dir", type=Path, default=DEFAULT_RESULTS)
    args = parser.parse_args()
    results = args.results_dir
    payload = json.loads((results / "scaling_raw.json").read_text())
    validate(payload, results)

    grouped: dict[tuple[str, int], list[dict[str, Any]]] = defaultdict(list)
    for row in payload["records"]:
        grouped[(str(row["benchmark"]), int(row["n"]))].append(row)
    summary: dict[str, Any] = {
        "schema_version": 1,
        "experiment": payload["experiment"],
        "measurement_scope": payload["measurement_scope"],
        "external_call_semantics": payload["external_call_semantics"],
        "limitations": payload["limitations"],
        "seed": payload["seed"],
        "sizes": payload["sizes"],
        "repetitions": payload["repetitions"],
        "quantile_method": "linear interpolation on zero-indexed ranks",
        "all_vectors_exact": True,
        "raw_samples": len(payload["records"]),
        "platform": payload["platform"],
        "source_sha256": payload["source_sha256"],
    }
    for benchmark in BENCHMARKS:
        summary[benchmark] = []
        for n in payload["sizes"]:
            item = summarize_rows(grouped[(benchmark, int(n))])
            item["n"] = int(n)
            summary[benchmark].append(item)
    (results / "scaling_summary.json").write_text(json.dumps(summary, indent=2) + "\n")
    write_tables(results, summary)
    print(
        f"PASS: summarized {summary['raw_samples']} in-memory samples; "
        "all expected vectors were exact"
    )


if __name__ == "__main__":
    main()
