#!/usr/bin/env python3
"""Validate and summarize the live Kind fleet adapter experiment."""

from __future__ import annotations

import argparse
import csv
import json
import math
import statistics
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_RESULTS = ROOT / "lab" / "results_live_fleet"


def quantile(values: list[float], probability: float) -> float:
    if not values:
        raise ValueError("empty sample")
    ordered = sorted(values)
    position = (len(ordered) - 1) * probability
    low, high = math.floor(position), math.ceil(position)
    if low == high:
        return ordered[low]
    weight = position - low
    return ordered[low] * (1.0 - weight) + ordered[high] * weight


def timing(rows: list[dict[str, Any]], field: str) -> dict[str, float]:
    values = [float(row[field]) for row in rows]
    return {
        "p50": quantile(values, 0.50),
        "p95": quantile(values, 0.95),
        "mean": statistics.fmean(values),
    }


def verify_csv(results: Path, rows: list[dict[str, Any]]) -> None:
    with (results / "live_fleet_raw.csv").open(newline="") as handle:
        csv_rows = list(csv.DictReader(handle))
    if len(csv_rows) != len(rows):
        raise SystemExit("live-fleet raw CSV/JSON row counts differ")
    keys = list(csv_rows[0]) if csv_rows else []
    for index, (csv_row, json_row) in enumerate(zip(csv_rows, rows), start=1):
        if csv_row != {key: str(json_row[key]) for key in keys}:
            raise SystemExit(f"live-fleet CSV differs from JSON at row {index}")


def validate(payload: dict[str, Any], results: Path) -> None:
    scope = payload.get("measurement_scope", "")
    for phrase in ("one Deployment LIST", "one Pod LIST", "not a Flux/Kyverno"):
        if phrase not in scope:
            raise SystemExit(f"measurement boundary omits {phrase!r}")
    rows = payload.get("rows", [])
    completed = [int(value) for value in payload.get("completed_sizes", [])]
    expected_sweeps = int(payload["sweeps_per_completed_size"])
    by_n = Counter(int(row["n"]) for row in rows)
    for n in completed:
        if by_n[n] != expected_sweeps:
            raise SystemExit(f"completed n={n} has {by_n[n]} rather than {expected_sweeps} sweeps")
    seen = set()
    for row in rows:
        key = (int(row["n"]), int(row["sweep"]))
        if key in seen:
            raise SystemExit(f"duplicate live-fleet row {key}")
        seen.add(key)
        if bool(row["api_error"]):
            raise SystemExit(f"API error in measured sweep {key}: {row['error_detail']}")
        if int(row["exact_vectors"]) != int(row["expected_vectors"]):
            raise SystemExit(f"non-exact baseline vector at {key}")
        if int(row["epistemic_vectors"]) != 0:
            raise SystemExit(f"unexpected epistemic vector at {key}")
        if int(row["policy_fanout_exact_vectors"]) != int(row["policy_fanout_units"]):
            raise SystemExit(f"non-exact policy fan-out at {key}")
        if int(row["api_command_count"]) != 1 or int(row["modeled_api_list_operations"]) != 2:
            raise SystemExit(f"unexpected fetch call accounting at {key}")
    cleanup = payload.get("cleanup", {})
    if not cleanup.get("attempted") or not cleanup.get("namespace_absent_after"):
        raise SystemExit("exclusive namespace cleanup is not verified")
    verify_csv(results, rows)


def fmt_rate(value: float) -> str:
    return f"{value:,.0f}".replace(",", r"\,")


def write_tables(results: Path, summary: dict[str, Any]) -> None:
    lines = [
        "% Generated by scripts/analyze_live_fleet.py.",
        r"\begin{tabular}{@{}rrrrrrrrrrrrr@{}}",
        r"\toprule",
        "$n$ & Sweeps & Pods & Containers & Fetch P50 & Fetch P95 & Parse P50 & Parse P95 & "
        "Core P50 & Core P95 & Total P50 & Total P95 & Units/s \\\\",
        r"\midrule",
    ]
    for row in summary["sizes"]:
        pods = f"{row['active_pods_min']}--{row['active_pods_max']}"
        containers = f"{row['active_containers_min']}--{row['active_containers_max']}"
        lines.append(
            f"{row['n']} & {row['sweeps']} & {pods} & {containers} & "
            f"{row['fetch_ms']['p50']:.2f} & {row['fetch_ms']['p95']:.2f} & "
            f"{row['parse_ms']['p50']:.2f} & {row['parse_ms']['p95']:.2f} & "
            f"{row['core_ms']['p50']:.3f} & {row['core_ms']['p95']:.3f} & "
            f"{row['total_ms']['p50']:.2f} & {row['total_ms']['p95']:.2f} & "
            f"{fmt_rate(row['units_per_second_median'])} \\\\"
        )
    lines += [r"\bottomrule", r"\end{tabular}"]
    (results / "table_live_fleet.tex").write_text("\n".join(lines) + "\n")

    fanout = [
        "% Generated by scripts/analyze_live_fleet.py; policy delta is synthetic in-memory.",
        r"\begin{tabular}{@{}rrrrrr@{}}",
        r"\toprule",
        "$n$ & Sweeps & Seeded $k$ & Core P50 ms & Core P95 ms & Exact vectors \\\\",
        r"\midrule",
    ]
    for row in summary["sizes"]:
        fanout.append(
            f"{row['n']} & {row['sweeps']} & {row['policy_fanout_units']} & "
            f"{row['policy_fanout_core_ms']['p50']:.3f} & "
            f"{row['policy_fanout_core_ms']['p95']:.3f} & "
            f"{row['policy_fanout_exact_total']}/{row['policy_fanout_expected_total']} \\\\"
        )
    fanout += [r"\bottomrule", r"\end{tabular}"]
    (results / "table_live_fleet_fanout.tex").write_text("\n".join(fanout) + "\n")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--results-dir", type=Path, default=DEFAULT_RESULTS)
    args = parser.parse_args()
    results = args.results_dir
    payload = json.loads((results / "live_fleet_raw.json").read_text())
    validate(payload, results)

    grouped: dict[int, list[dict[str, Any]]] = defaultdict(list)
    for row in payload["rows"]:
        grouped[int(row["n"])].append(row)
    sizes = []
    for n in sorted(grouped):
        rows = grouped[n]
        sizes.append(
            {
                "n": n,
                "sweeps": len(rows),
                "phases": dict(Counter(str(row["phase"]) for row in rows)),
                "fetch_ms": timing(rows, "fetch_ms"),
                "parse_ms": timing(rows, "parse_ms"),
                "core_ms": timing(rows, "core_ms"),
                "total_ms": timing(rows, "total_ms"),
                "units_per_second_median": statistics.median(
                    float(row["units_per_second"]) for row in rows
                ),
                "active_pods_min": min(int(row["active_pods"]) for row in rows),
                "active_pods_max": max(int(row["active_pods"]) for row in rows),
                "active_containers_min": min(int(row["active_containers"]) for row in rows),
                "active_containers_max": max(int(row["active_containers"]) for row in rows),
                "response_bytes_p50": quantile(
                    [float(row["response_bytes"]) for row in rows], 0.50
                ),
                "response_bytes_p95": quantile(
                    [float(row["response_bytes"]) for row in rows], 0.95
                ),
                "exact_vectors": sum(int(row["exact_vectors"]) for row in rows),
                "expected_vectors": sum(int(row["expected_vectors"]) for row in rows),
                "api_errors": sum(bool(row["api_error"]) for row in rows),
                "api_commands": sum(int(row["api_command_count"]) for row in rows),
                "modeled_api_list_operations": sum(
                    int(row["modeled_api_list_operations"]) for row in rows
                ),
                "policy_fanout_units": int(rows[0]["policy_fanout_units"]),
                "policy_fanout_core_ms": timing(rows, "policy_fanout_core_ms"),
                "policy_fanout_exact_total": sum(
                    int(row["policy_fanout_exact_vectors"]) for row in rows
                ),
                "policy_fanout_expected_total": sum(
                    int(row["policy_fanout_units"]) for row in rows
                ),
            }
        )

    summary = {
        "schema_version": 1,
        "experiment": payload["experiment"],
        "measurement_scope": payload["measurement_scope"],
        "status": payload["status"],
        "requested_sizes": payload["requested_sizes"],
        "completed_sizes": payload["completed_sizes"],
        "seed": payload["seed"],
        "raw_sweeps": len(payload["rows"]),
        "all_vectors_exact": all(
            int(row["exact_vectors"]) == int(row["expected_vectors"])
            for row in payload["rows"]
        ),
        "all_policy_fanouts_exact": all(
            int(row["policy_fanout_exact_vectors"]) == int(row["policy_fanout_units"])
            for row in payload["rows"]
        ),
        "api_errors": len(payload["api_errors"]),
        "quantile_method": "linear interpolation on zero-indexed ranks",
        "stop_rules": payload["stop_rules"],
        "churn_schedule": payload["churn_schedule"],
        "limitations": payload["limitations"],
        "platform": payload["platform"],
        "resource_checks": payload["resource_checks"],
        "cleanup": payload["cleanup"],
        "sizes": sizes,
    }
    (results / "live_fleet_summary.json").write_text(json.dumps(summary, indent=2) + "\n")
    write_tables(results, summary)
    print(
        f"PASS: {summary['raw_sweeps']} live sweeps, sizes={summary['completed_sizes']}, "
        f"API errors={summary['api_errors']}, cleanup verified"
    )


if __name__ == "__main__":
    main()
