#!/usr/bin/env python3
"""Validate and summarize the compound live-lab extension and benign soak."""

from __future__ import annotations

import argparse
import csv
import json
import math
import statistics
from collections import Counter
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
EXPECTED = {
    "S10": "policy|authorization",
    "S11": "authorization|environment",
    "S12": "intent|evidence",
}
CADENCES = (0.5, 2.0, 10.0)


def as_bool(value: object) -> bool:
    return value is True or str(value).lower() == "true"


def p95(values: list[float]) -> float:
    ordered = sorted(values)
    return ordered[max(0, math.ceil(0.95 * len(ordered)) - 1)]


def tex_set(value: str) -> str:
    labels = ["auth." if item == "authorization" else item for item in value.split("|")]
    return r"\{" + ", ".join(labels) + r"\}"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--results", type=Path, default=ROOT / "lab" / "results_extension"
    )
    args = parser.parse_args()
    source = args.results / "repeated_observations.json"
    payload = json.loads(source.read_text())
    positives = payload["positive_rows"]
    controls = payload["control_rows"]

    if payload.get("repetitions_per_scenario") != 5:
        raise SystemExit("extension must contain five repetitions per scenario")
    if len(positives) != 45:
        raise SystemExit("extension must contain 45 cadence observations")
    if {row["scenario"] for row in positives} != set(EXPECTED):
        raise SystemExit("extension scenario set differs from S10--S12")
    if any(not as_bool(row["detection_rate_hit"]) for row in positives):
        raise SystemExit("compound extension contains a detection miss")
    if any(not as_bool(row["classification_correct"]) for row in positives):
        raise SystemExit("compound extension contains an incorrect completed class set")
    for row in positives:
        if set(row["observed_class_set"].split("|")) != set(EXPECTED[row["scenario"]].split("|")):
            raise SystemExit(f"{row['scenario']}: final class set differs from ground truth")
        if float(row["exact_set_complete_seconds"]) < float(row["ddl_seconds"]):
            raise SystemExit(f"{row['scenario']}: class set completed before first detection")

    if payload.get("control_windows") != 6 or float(payload.get("control_window_seconds")) != 300.0:
        raise SystemExit("soak must contain six 300-second control windows")
    if len(controls) != 18:
        raise SystemExit("soak must contain three cadence rows for each of six windows")
    if any(int(row["alarms"]) or int(row.get("epistemic_warnings", 0)) for row in controls):
        raise SystemExit("soak contains an alarm or epistemic warning")

    summaries = []
    lines = [
        "% Generated by scripts/analyze_lab_extension.py",
        r"\begin{tabular}{@{}llrrrrrrrr@{}}",
        r"\toprule",
        r"ID & Expected set & Inj. & Obs. & DR & Exact & First complete & Med. DDL & Med. ESC & Med. DG \\",
        r"\midrule",
    ]
    for scenario, expected in EXPECTED.items():
        rows = [row for row in positives if row["scenario"] == scenario]
        first_complete = sum(
            set(row["first_observed_class_set"].split("|")) == set(expected.split("|"))
            for row in rows
        )
        ddl = [float(row["ddl_seconds"]) for row in rows]
        completion = [float(row["exact_set_complete_seconds"]) for row in rows]
        diagnostic_gap = [complete - first for complete, first in zip(completion, ddl)]
        first_sets = Counter(row["first_observed_class_set"] for row in rows)
        item = {
            "scenario": scenario,
            "expected_class_set": expected,
            "observations": len(rows),
            "injections": len({int(row["repeat"]) for row in rows}),
            "detections": sum(as_bool(row["detection_rate_hit"]) for row in rows),
            "exact_completed_class_sets": sum(as_bool(row["classification_correct"]) for row in rows),
            "first_complete_class_sets": first_complete,
            "first_observed_sets": dict(sorted(first_sets.items())),
            "ddl_median_seconds": statistics.median(ddl),
            "ddl_p95_seconds": p95(ddl),
            "exact_set_completion_median_seconds": statistics.median(completion),
            "exact_set_completion_p95_seconds": p95(completion),
            "diagnostic_gap_median_seconds": statistics.median(diagnostic_gap),
            "diagnostic_gap_p95_seconds": p95(diagnostic_gap),
        }
        summaries.append(item)
        lines.append(
            f"{scenario} & {tex_set(expected)} & {item['injections']} & {len(rows)} & "
            f"{100*item['detections']/len(rows):.1f}\% & "
            f"{100*item['exact_completed_class_sets']/len(rows):.1f}\% & "
            f"{100*first_complete/len(rows):.1f}\% & "
            f"{item['ddl_median_seconds']:.2f} & "
            f"{item['exact_set_completion_median_seconds']:.2f} & "
            f"{item['diagnostic_gap_median_seconds']:.2f} \\\\"
        )
    lines += [r"\bottomrule", r"\end{tabular}"]
    (args.results / "table_compound.tex").write_text("\n".join(lines) + "\n")

    summary = {
        "design": "five repetitions of S10--S12 at three cadences; six 300-second benign windows",
        "positive_observations": len(positives),
        "detected": sum(as_bool(row["detection_rate_hit"]) for row in positives),
        "exact_completed_class_sets": sum(as_bool(row["classification_correct"]) for row in positives),
        "first_complete_class_sets": sum(
            set(row["first_observed_class_set"].split("|"))
            == set(EXPECTED[row["scenario"]].split("|"))
            for row in positives
        ),
        "scenarios": summaries,
        "soak": {
            "windows": len({int(row["window"]) for row in controls}),
            "seconds": sum(
                float(next(row["duration_seconds"] for row in controls if int(row["window"]) == window))
                for window in {int(row["window"]) for row in controls}
            ),
            "polls": sum(int(row["polls"]) for row in controls),
            "substantive_alarms": sum(int(row["alarms"]) for row in controls),
            "epistemic_warnings": sum(int(row.get("epistemic_warnings", 0)) for row in controls),
        },
    }
    (args.results / "extension_summary.json").write_text(json.dumps(summary, indent=2) + "\n")

    with (args.results / "repeated_observations.csv").open(newline="") as handle:
        csv_rows = list(csv.DictReader(handle))
    if len(csv_rows) != len(positives):
        raise SystemExit("extension CSV/JSON row counts differ")
    print(json.dumps(summary, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
